version: '2'
services:
  webhook:
    image: rancher/dns-service
    links:
    - webhook-lb:webhook-lb
  webhook-lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 8040:8040/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
  webhook-proxy:
    image: flaccid/slack-incoming-webhook-proxy
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
